backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads" 
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "עמודים"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "כותרת", name: "title", widget: "string" }
      - { label: "תוכן", name: "body", widget: "markdown" }